# Generated by Django 3.1 on 2022-09-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('colour', 'colour'), ('size', 'size'), ('length', 'logo')], max_length=200),
        ),
    ]
