# Generated by Django 3.1 on 2022-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220928_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=85122),
            preserve_default=False,
        ),
    ]
