# Generated by Django 3.1 on 2022-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220928_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
